#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/dcclient.h>
#include <wx/textfile.h>
#include <wx/log.h>
#include <wx/colour.h>
#include <wx/filedlg.h>
#include <fstream>
#include <string>
#include <stdlib.h>
#include <algorithm>
#include <thread>
#include <chrono>
#include <wx/dcmemory.h>


/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void loadFileOnButtonClick( wxCommandEvent& event );
		void startAnimOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
	private:
		void Repaint();
		void FileParser(const std::string& filename);
		void SetPanelSize(int width, int heigt);
		void DrawPoint(int x, int y);
		void DrawLine(int x1, int y1, int x2, int y2);
		void DrawRectangle(int x1, int y1, int x2, int y2, int flag);
		void DrawElipse(int x1, int y1, int x2, int y2, int flag);
		void SaveClientDCToBitmap(wxString filename);
		wxString _filename;
		wxColour _penColor;
		int _penSize;
		wxColour _fillColor;








};

#endif // __GUIMyFrame1__
